name: Create Windows RDP session for student

on:
  push:
    branches:
      - main

jobs:
  create-rdp-session:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up RDP server
        uses: actions/setup-powershell@v3
        with:
          powershell-version: latest

      - name: Install RDP server dependencies
        run: |
          powershell.exe -ExecutionPolicy Bypass -Command "Add-WindowsFeature -Name Remote-Desktop-Services"

      - name: Enable RDP server
        run: powershell.exe -ExecutionPolicy Bypass -Command "Enable-NetFirewallRule -Name Remote-Desktop-UserMode -Enabled True"

      - name: Create RDP user account
        run: |
          powershell.exe -ExecutionPolicy Bypass -Command "New-LocalUser -Name 'student' -Password 'password'"

      - name: Add RDP user to Remote Desktop Users group
        run: powershell.exe -ExecutionPolicy Bypass -Command "Add-LocalUserMemberGroup -Principal student -MemberName Remote Desktop Users"

      - name: Get RDP server IP address
        id: get-ip-address
        run: powershell.exe -ExecutionPolicy Bypass -Command "Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias Ethernet | Where-Object {$_.IPv4Address -ne $null} | Select-Object -First 1"
        outputs:
          ip_address: ${{ steps.get-ip-address.outputs.ip_address }}

      - name: Create RDP session URL
        id: create-rdp-url
        run: echo "mstsc://${{ steps.get-ip-address.outputs.ip_address }}:3389"
        outputs:
          rdp_url: ${{ steps.create-rdp-url.outputs.rdp_url }}

      - name: Output RDP session URL
        run: echo "RDP session URL: ${{ steps.create-rdp-url.outputs.rdp_url }}"
