name: Create Windows RDP session for student

on:
  push:
    branches:
      - main

jobs:
  create-rdp-session:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v3
        with:
          powershell-version: latest

      - name: Install RDP server dependencies
        run: |
          powershell.exe -ExecutionPolicy Bypass -Command "Add-WindowsFeature -Name Remote-Desktop-Services"

      - name: Enable RDP server
        run: powershell.exe -ExecutionPolicy Bypass -Command "Enable-NetFirewallRule -Name Remote-Desktop-UserMode -Enabled True"

      - name: Create RDP user account
        run: |
          powershell.exe -ExecutionPolicy Bypass -Command "New-LocalUser -Name 'student' -Password (ConvertTo-SecureString -AsPlainText 'password' -Force)"

      - name: Add RDP user to Remote Desktop Users group
        run: powershell.exe -ExecutionPolicy Bypass -Command "Add-LocalGroupMember -Group 'Remote Desktop Users' -Member 'student'"

      - name: Get RDP server IP address
        id: get-ip-address
        run: |
          $ipAddress = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias Ethernet | Where-Object { $_.IPv4Address -ne $null }).IPv4Address
          Write-Output "IP_ADDRESS=$ipAddress"
        shell: powershell
        env:
          PowerShellOption: '-NoProfile -NonInteractive -ExecutionPolicy Bypass'

      - name: Create RDP session URL
        id: create-rdp-url
        run: |
          $ipAddress = $env:IP_ADDRESS
          Write-Output "RDP_URL=mstsc://$ipAddress:3389"
        shell: powershell
        env:
          PowerShellOption: '-NoProfile -NonInteractive -ExecutionPolicy Bypass'

      - name: Output RDP session URL
        run: echo "RDP session URL: ${{ env.RDP_URL }}"
